on:
  push:
    tags:
      - '*'

env:
 pushed_tag: ${{  github.ref_name }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:  
    - name: Release 생성 
      uses: actions/create-release@v1
      env: 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with: 
        tag_name: ${{ env.pushed_tag }}
        release_name: ${{ env.pushed_tag }}
        draft: false
        prerelease: false
